config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "countries#index"
  resources "countries",  only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_api_football, :set_countries

  def index
    @countries
  end

  def show
    @country = @countries[params["id"].to_i]
    @leagues = LeaguesHelper::LeagueData.new.leagues({code: @country["code"]})["response"]
  end

  private

  def set_api_football
    @api_football_country = CountriesHelper::CountryData.new
  end

  def set_countries
    @countries = @api_football_country.countries["response"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class APIFootball
    include HTTParty
    API_KEY = Rails.application.credentials.api_sports.football[:key]
    base_uri  "https://v3.football.api-sports.io/"
    headers   "x-apisports-key" => API_KEY
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
  class CountryData < ApplicationHelper::APIFootball
    ENDPOINT = "/countries".freeze

    def countries(options = {})
      #debugger
      queries = { query: options }

      self.class.get(ENDPOINT, queries)
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  class LeagueData < ApplicationHelper::APIFootball
    ENDPOINT = "/leagues".freeze

    def leagues(options = {})
      defualt_queries = { "type" => "league", "current" => "true" }
      queries = { query: defualt_queries.merge(options) }

      self.class.get(ENDPOINT, queries)
    end
  end
end

app/views/countries/index.html.erb
<h1>Footballing Countries</h1>
<p>Check one of the <%= @countries.size %> countries to view their leagues and club teams!</p>

<div class="countries">
  <% if @countries %>
    <% @countries.each_with_index do |country, idx| %>
      <div class="country">
        <p>
          <%= country["name"] %> (<%= country["code"] %>) |
          <%= image_tag(country["flag"],
                        size: "25", 
                        alt: "<#{country["name"]}> flag") if country["flag"] 
                        %>
          <%= link_to "View Country", country_path(idx) %>
        </p>
      </div>
    <% end %>
  <% else %>
    <p>No data available</p>
  <% end %>
</div>

app/views/countries/show.html.erb
<h1><%= @country["name"] %> | <%= @country["code"] %></h1>

<p>
<%= image_tag(@country["flag"],
              size: "50", 
              alt: "<#{@country["name"]}> flag") if @country["flag"] 
              %>
</p>

<hr />

<p>Check out the Leagues and the clubs competing within:</p>

<div class="leagues">
  <% if @leagues %>
    <% @leagues.each do |league| %>
      <div class="league">
        <p>
          <%= league["league"]["name"] %> (<%= league["league"]["type"] %>)
          <%= image_tag(league["league"]["logo"],
                        size: "25", 
                        alt: "<#{league["league"]["name"]}> flag") if league["league"]["logo"] 
                        %>
        </p>
      </div>
    <% end %>
  <% else %>
    <p>There are no leagues to display</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>